############# navigation ##############

# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Nosotros"
url = "about/"
weight = 2

[[main]]
name = "Servicio"
url = "service/"
weight = 3

[[main]]
name = "Proyectos"
url = "proyectos/"
weight = 3

# footer menu
[[footer]]
name = "Nosotros"
url = "about/"
weight = 1

[[footer]]
name = "Contactanos"
url = "contact/"
weight = 2

[[footer]]
name = "Privacidad"
url = "privacy-policy/"
weight = 3
