############# navigation ##############

# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Sobre mi"
url = "about/"
weight = 2

[[main]]
name = "Cursos"
url = "elements/"
weight = 3

# footer menu
[[footer]]
name = "Sobre mi"
url = "about/"
weight = 1

[[footer]]
name = "Contactanos"
url = "contact/"
weight = 2

[[footer]]
name = "Privacidad"
url = "privacy-policy/"
weight = 3
